sudo: required
language: generic
matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          dist: trusty          
          env: VERSION=6
        - os: linux
          dist: trusty          
          env: VERSION=7
        - os: linux
          dist: trusty          
          env: VERSION=5
        # Use generic language for osx
        - os: osx
          osx_image: xcode8
          language: generic

install:
    - bash script/install-unix.sh
    - wget -O - https://raw.githubusercontent.com/Zefiros-Software/ZPM/master/script/install-zpm-travis.sh | bash
script:
    - bash script/travis-build.sh
notifications:
    slack:
        secure: "HApkrF/Pji6d2KdbdmzpL4CQ0wOWGOMzJ7uH+AQa7c0kHdMP9vkRaz3R3lGX/STTew+fQiJkpjmZVNLSlSUbnnUVlhLtn+pMPCgb4YyUu71u0ZSzKIs003nF0WFreQApMccfR6XkbfRK/VMf+xzPzxfu1587QP7ExMlAeHXKwqljYYFchL1wKNMbvPgzACu9Yduvvlm5zeLqt4IZXBiG9yMelGYP/dcy8ZVLHUtJAttXC+AU4P2xIgrx9DLDhN2mSeTkmw/RhHxAyehZXzJkDwnXuqhroVv5nxskV1UnoRqXkRZA9BTdqnDTAbjTv/WD+vLw4+fqjWEcNN/9pbEuM/rQRafewdB4TluUxd8S+tUoCGYwXnN+Uut00PXNCo2Tw6YGDBRvZhRL0OjL/hOcgYBu+NAJkd6LITN+w1BRmW5iOwrCd0s0J4G17GJi1+VVeS++wUK09Ks3awWcdA0ue23hYIxo47FxOs6l03a1Y03Dru2rC+AFTgIt6VLGN6MCPXW222TR6W/o2yuWC9MtPg7dvev+R9nkyGeV8n1t+R5dnoS8EKVk59hk9VS0YeRIgmahRsr7J/NdarKhMEM+x40vkGOoTHlD1vTlhxgBI/54V+9keOOx5QDiG/A/Z7Y8JIlqfLBY/FfLM6xUl9y+YN5BT6lsVBsRZBcC9JQ5C3M="